// HTML QUESTIONS

const htmlQuestions = [

{question:"What does HTML stand for?",options:["Hyper Text Markup Language","High Text Markup Language","Hyper Transfer Markup Language","None"],answer:"Hyper Text Markup Language"},
{question:"Which tag creates a hyperlink?",options:["<link>","<a>","<href>","<url>"],answer:"<a>"},
{question:"Which tag inserts an image?",options:["<img>","<image>","<pic>","<src>"],answer:"<img>"},
{question:"Largest heading tag?",options:["<h6>","<head>","<h1>","<title>"],answer:"<h1>"},
{question:"Paragraph tag?",options:["<para>","<p>","<text>","<pg>"],answer:"<p>"},
{question:"Line break tag?",options:["<break>","<lb>","<br>","<newline>"],answer:"<br>"},
{question:"HTML file extension?",options:[".html",".ht",".web",".h"],answer:".html"},
{question:"List item tag?",options:["<li>","<ul>","<ol>","<list>"],answer:"<li>"},
{question:"Ordered list tag?",options:["<ul>","<ol>","<li>","<list>"],answer:"<ol>"},
{question:"Unordered list tag?",options:["<ul>","<ol>","<li>","<list>"],answer:"<ul>"},
{question:"Table row tag?",options:["<tr>","<td>","<th>","<table>"],answer:"<tr>"},
{question:"Table data tag?",options:["<td>","<tr>","<th>","<table>"],answer:"<td>"},
{question:"Table heading tag?",options:["<td>","<tr>","<th>","<table>"],answer:"<th>"},
{question:"Form tag?",options:["<form>","<input>","<button>","<label>"],answer:"<form>"},
{question:"Text input type?",options:["text","textbox","string","input"],answer:"text"},
{question:"Checkbox type?",options:["check","checkbox","tick","select"],answer:"checkbox"},
{question:"Radio button type?",options:["radio","option","circle","choice"],answer:"radio"},
{question:"HTML comment starts with?",options:["<!--","//","##","/*"],answer:"<!--"},
{question:"Page title tag?",options:["<head>","<title>","<meta>","<body>"],answer:"<title>"},
{question:"Body content tag?",options:["<head>","<html>","<body>","<main>"],answer:"<body>"},
{question:"Root tag?",options:["<root>","<html>","<head>","<body>"],answer:"<html>"},
{question:"Bold tag?",options:["<b>","<strong>","Both","None"],answer:"Both"},
{question:"Italic tag?",options:["<i>","<italic>","<it>","<emphasis>"],answer:"<i>"},
{question:"Underline tag?",options:["<u>","<underline>","<un>","<ul>"],answer:"<u>"},
{question:"Horizontal line tag?",options:["<line>","<hr>","<br>","<hl>"],answer:"<hr>"},
{question:"HTML is?",options:["Programming Language","Markup Language","Database","OS"],answer:"Markup Language"},
{question:"Attribute for image path?",options:["href","src","link","path"],answer:"src"},
{question:"Attribute for hyperlink?",options:["src","href","link","url"],answer:"href"},
{question:"HTML5 introduced?",options:["Video & Audio","Tables","Forms","Lists"],answer:"Video & Audio"},
{question:"HTML developed by?",options:["Google","Microsoft","W3C","Oracle"],answer:"W3C"}

];
const cssQuestions = [

{question:"CSS stands for?",options:["Creative Style Sheets","Cascading Style Sheets","Computer Style Sheets","Colorful Style Sheets"],answer:"Cascading Style Sheets"},
{question:"Property for text color?",options:["font-color","color","text-color","foreground"],answer:"color"},
{question:"Background color property?",options:["bgcolor","background-color","background","color"],answer:"background-color"},
{question:"Class selector symbol?",options:["#",".","*","@"],answer:"."},
{question:"ID selector symbol?",options:["#",".","*","@"],answer:"#"},
{question:"Universal selector?",options:["#","*",".","@"],answer:"*"},
{question:"CSS file extension?",options:[".css",".style",".cs",".c"],answer:".css"},
{question:"Property for font size?",options:["size","font-size","text-size","fontsize"],answer:"font-size"},
{question:"Property for alignment?",options:["align","text-align","position","float"],answer:"text-align"},
{question:"Property for margin?",options:["margin","padding","space","gap"],answer:"margin"},
{question:"Property for padding?",options:["margin","padding","gap","space"],answer:"padding"},
{question:"Property for border?",options:["outline","border","frame","line"],answer:"border"},
{question:"Display block element?",options:["block","inline","flex","grid"],answer:"block"},
{question:"Display inline element?",options:["inline","block","flex","grid"],answer:"inline"},
{question:"Property to hide element?",options:["display:none","hide:true","visible:false","opacity:0"],answer:"display:none"},
{question:"Position property value?",options:["absolute","center","left","top"],answer:"absolute"},
{question:"Flexbox property?",options:["display:flex","display:block","display:inline","display:grid"],answer:"display:flex"},
{question:"Grid property?",options:["display:grid","display:flex","display:block","display:inline"],answer:"display:grid"},
{question:"CSS comment?",options:["/* */","//","<!-- -->","##"],answer:"/* */"},
{question:"Property for width?",options:["width","size","length","w"],answer:"width"},
{question:"Property for height?",options:["height","size","length","h"],answer:"height"},
{question:"Property for background image?",options:["background-image","image","bg-image","img"],answer:"background-image"},
{question:"Property for opacity?",options:["opacity","transparent","alpha","visible"],answer:"opacity"},
{question:"Property for shadow?",options:["shadow","box-shadow","text-shadow","effect"],answer:"box-shadow"},
{question:"Property for rounded corners?",options:["border-radius","radius","curve","corner"],answer:"border-radius"},
{question:"Pseudo class hover?",options:[":hover",".hover","hover","#hover"],answer:":hover"},
{question:"Property for font family?",options:["font","font-family","family","font-style"],answer:"font-family"},
{question:"Property for font weight?",options:["font-weight","weight","bold","font-bold"],answer:"font-weight"},
{question:"External CSS uses?",options:["<style>","<link>","<css>","<script>"],answer:"<link>"},
{question:"CSS is used for?",options:["Structure","Styling","Database","Programming"],answer:"Styling"}

];
const jsQuestions = [

{question:"JavaScript is a?",options:["Programming Language","Markup Language","Database","OS"],answer:"Programming Language"},
{question:"Which keyword declares a variable?",options:["var","int","string","float"],answer:"var"},
{question:"Modern variable keyword?",options:["let","dim","define","consts"],answer:"let"},
{question:"Constant variable keyword?",options:["fixed","const","constant","final"],answer:"const"},
{question:"Output function?",options:["print()","alert()","display()","show()"],answer:"alert()"},
{question:"Console output method?",options:["console.print()","console.log()","log.console()","print.log()"],answer:"console.log()"},
{question:"JavaScript code is written inside?",options:["<javascript>","<script>","<js>","<code>"],answer:"<script>"},
{question:"Single line comment?",options:["//","/*","<!--","##"],answer:"//"},
{question:"Multi-line comment?",options:["/* */","//","<!-- -->","##"],answer:"/* */"},
{question:"Which symbol is assignment operator?",options:["=","==","===","!="],answer:"="},
{question:"Equality operator?",options:["=","==","+=","!="],answer:"=="},
{question:"Strict equality operator?",options:["===","==","=","!=="],answer:"==="},
{question:"Not equal operator?",options:["!=","=","==","<"],answer:"!="},
{question:"Function keyword?",options:["function","func","method","define"],answer:"function"},
{question:"Array starts with?",options:["{}","[]","()","<>"],answer:"[]"},
{question:"Object starts with?",options:["{}","[]","()","<>"],answer:"{}"},
{question:"Method to get element by ID?",options:["getElementById()","queryID()","findID()","selectID()"],answer:"getElementById()"},
{question:"Popup input box?",options:["alert()","prompt()","confirm()","input()"],answer:"prompt()"},
{question:"Confirmation box?",options:["alert()","prompt()","confirm()","input()"],answer:"confirm()"},
{question:"Event for button click?",options:["onclick","onhover","onchange","onload"],answer:"onclick"},
{question:"Loop keyword?",options:["for","repeat","loop","iterate"],answer:"for"},
{question:"Conditional statement?",options:["if","check","when","condition"],answer:"if"},
{question:"Else block keyword?",options:["otherwise","else","elif","other"],answer:"else"},
{question:"JavaScript file extension?",options:[".js",".javascript",".java",".jsx"],answer:".js"},
{question:"Parse integer function?",options:["parseInt()","int()","convertInt()","number()"],answer:"parseInt()"},
{question:"Length property?",options:["size","count","length","total"],answer:"length"},
{question:"DOM stands for?",options:["Document Object Model","Data Object Model","Document Order Method","Display Object Model"],answer:"Document Object Model"},
{question:"Window object represents?",options:["Browser Window","File","Database","Array"],answer:"Browser Window"},
{question:"JavaScript can change HTML?",options:["Yes","No","Sometimes","Only CSS"],answer:"Yes"},
{question:"JavaScript is mainly used for?",options:["Styling","Interactivity","Database","Networking"],answer:"Interactivity"}

];
const webQuestions = [

{question:"Web development includes?",options:["Frontend","Backend","Both","None"],answer:"Both"},
{question:"Frontend technologies are?",options:["HTML CSS JS","Java SQL","Python PHP","Oracle"],answer:"HTML CSS JS"},
{question:"Backend handles?",options:["Logic","Styling","Design","Animation"],answer:"Logic"},
{question:"HTML is used for?",options:["Structure","Style","Database","Server"],answer:"Structure"},
{question:"CSS is used for?",options:["Styling","Database","Programming","Hosting"],answer:"Styling"},
{question:"JavaScript is used for?",options:["Interactivity","Storage","Server","Database"],answer:"Interactivity"},
{question:"URL stands for?",options:["Uniform Resource Locator","Universal Resource Locator","Uniform Record Locator","Universal Record Link"],answer:"Uniform Resource Locator"},
{question:"HTTP stands for?",options:["Hyper Text Transfer Protocol","High Text Transfer Protocol","Hyper Transfer Text Program","Hyper Text Transmission Process"],answer:"Hyper Text Transfer Protocol"},
{question:"HTTPS adds?",options:["Security","Speed","Storage","Database"],answer:"Security"},
{question:"Domain name example?",options:["google.com","HTML","CSS","JS"],answer:"google.com"},
{question:"Browser example?",options:["Chrome","HTML","CSS","PHP"],answer:"Chrome"},
{question:"Server stores?",options:["Website Files","Keyboard","Mouse","Printer"],answer:"Website Files"},
{question:"Database example?",options:["MySQL","HTML","CSS","Bootstrap"],answer:"MySQL"},
{question:"Responsive design means?",options:["Works on all devices","Fast loading","Secure","Offline"],answer:"Works on all devices"},
{question:"Framework example?",options:["Bootstrap","HTML","CSS","MySQL"],answer:"Bootstrap"},
{question:"Bootstrap is used for?",options:["Responsive Design","Database","Hosting","Backend"],answer:"Responsive Design"},
{question:"Website homepage file?",options:["index.html","home.html","main.html","start.html"],answer:"index.html"},
{question:"SEO stands for?",options:["Search Engine Optimization","System Engine Optimization","Search Easy Operation","Site Engine Output"],answer:"Search Engine Optimization"},
{question:"Hosting means?",options:["Publishing Website","Designing","Coding","Testing"],answer:"Publishing Website"},
{question:"Cloud storage example?",options:["Google Drive","HTML","CSS","JS"],answer:"Google Drive"},
{question:"Full form of WWW?",options:["World Wide Web","Web World Wide","Wide World Web","World Web Wide"],answer:"World Wide Web"},
{question:"Frontend runs on?",options:["Client Side","Server Side","Database","Cloud"],answer:"Client Side"},
{question:"Backend runs on?",options:["Server Side","Client Side","Browser","Device"],answer:"Server Side"},
{question:"Git is used for?",options:["Version Control","Database","Hosting","Design"],answer:"Version Control"},
{question:"GitHub is?",options:["Code Repository","Database","Browser","Server"],answer:"Code Repository"},
{question:"API stands for?",options:["Application Programming Interface","Advanced Program Integration","Application Process Interface","Application Program Internet"],answer:"Application Programming Interface"},
{question:"Testing ensures?",options:["Quality","Color","Design","Hosting"],answer:"Quality"},
{question:"UI stands for?",options:["User Interface","Unique Interface","User Internet","Universal Interface"],answer:"User Interface"},
{question:"UX stands for?",options:["User Experience","Universal Experience","User Extension","Unique Experience"],answer:"User Experience"},
{question:"Web development combines?",options:["Frontend + Backend","HTML + CSS","JS + SQL","All"],answer:"Frontend + Backend"}

];